apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k3s-certificate
spec:
  secretName: tls-certificate-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - kube.citizenscience.ch
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - kube.citizenscience.ch
