---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-c3s-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: encima@gmail.com
    privateKeySecretRef:
      name: letsencrypt-c3s-prod
    http01: {}
