apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: swaggerui-staging
  namespace: c3s-staging
  labels:
    app: swaggerui-staging-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: swaggerui-staging-app
  template:
    metadata:
      labels:
        app: swaggerui-staging-app
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: swaggerapi/swagger-ui
        ports:
        - containerPort: 8080
        env:
          - name: API_URL
            value: https://api-staging.citizenscience.ch/api/v2/openapi.json
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: swaggerui-staging-service
  namespace: c3s-staging
spec:
  selector:
    app: swaggerui-staging-app
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: swaggerui-staging-ingress
  namespace: c3s-staging
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/configuration-snippet: |
    #  more_set_headers "server: hide";
    #  more_set_headers "X-Content-Type-Options: nosniff";
    #  more_set_headers "X-Frame-Options: DENY";
    #  more_set_headers "X-Xss-Protection: 1";
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - openapi-staging.citizenscience.ch
    - www.openapi-staging.citizenscience.ch
    secretName: openapi-staging.citizenscience.ch
  rules:
  - host: openapi-staging.citizenscience.ch
    http:
      paths:
      - path: "/"
        backend:
          serviceName: swaggerui-staging-service
          servicePort: http
  - host: www.openapi-staging.citizenscience.ch
    http:
      paths:
      - path: "/"
        backend:
          serviceName: swaggerui-staging-service
          servicePort: http
