apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: swaggerui-prod
  namespace: c3s-prod
  labels:
    app: swaggerui-prod-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: swaggerui-prod-app
  template:
    metadata:
      labels:
        app: swaggerui-prod-app
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: swaggerapi/swagger-ui
        ports:
        - containerPort: 8080
        env:
        - name: API_URL
          value: https://api.citizenscience.ch/api/v2/swagger.json
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: swaggerui-prod-service
  namespace: c3s-prod
spec:
  selector:
    app: swaggerui-prod-app
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: swaggerui-prod-ingress
  namespace: c3s-prod
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/configuration-snippet: |
    #  more_set_headers "server: hide";
    #  more_set_headers "X-Content-Type-Options: nosniff";
    #  more_set_headers "X-Frame-Options: DENY";
    #  more_set_headers "X-Xss-Protection: 1";
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - explorer.citizenscience.ch
    - www.explorer.citizenscience.ch
    secretName: explorer.citizenscience.ch
  rules:
  - host: explorer.citizenscience.ch
    http:
      paths:
      - path: "/"
        backend:
          serviceName: swaggerui-prod-service
          servicePort: http
